[2024-07-30T18:53:20.291+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.monitoramento_task manual__2024-07-30T18:38:11.358353+00:00 [queued]>
[2024-07-30T18:53:20.299+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.monitoramento_task manual__2024-07-30T18:38:11.358353+00:00 [queued]>
[2024-07-30T18:53:20.299+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-30T18:53:20.299+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-30T18:53:20.299+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-30T18:53:20.309+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): monitoramento_task> on 2024-07-30 18:38:11.358353+00:00
[2024-07-30T18:53:20.316+0000] {standard_task_runner.py:55} INFO - Started process 13017 to run task
[2024-07-30T18:53:20.318+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_inmet', 'monitoramento_task', 'manual__2024-07-30T18:38:11.358353+00:00', '--job-id', '2880', '--raw', '--subdir', 'DAGS_FOLDER/dag_inmet.py', '--cfg-path', '/tmp/tmphpvtl40q']
[2024-07-30T18:53:20.319+0000] {standard_task_runner.py:83} INFO - Job 2880: Subtask monitoramento_task
[2024-07-30T18:53:20.360+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_inmet.monitoramento_task manual__2024-07-30T18:38:11.358353+00:00 [running]> on host 85c1c905ac53
[2024-07-30T18:53:20.408+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_inmet
AIRFLOW_CTX_TASK_ID=monitoramento_task
AIRFLOW_CTX_EXECUTION_DATE=2024-07-30T18:38:11.358353+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-30T18:38:11.358353+00:00
[2024-07-30T18:53:22.700+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
  warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)

[2024-07-30T18:53:22.799+0000] {dag_inmet.py:102} INFO - SparkSession criado com sucesso.
[2024-07-30T18:53:23.696+0000] {monitoramento_plugin.py:24} ERROR - Erro ao executar consulta Spark: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'Ã'.(line 2, pos 6)

== SQL ==
SELECT
  REGIÃO AS regiao,
------^^^
  UF AS uf,
  COUNT(ESTACAO) AS quantidade_estacoes,
  SUM(PRECIPITAÇAO) AS volumetria_safra
FROM gold_rainfall
WHERE DATA_FUNDACAO IS NOT NULL
GROUP BY REGIÃO, UF

[2024-07-30T18:53:23.699+0000] {dag_inmet.py:110} ERROR - Erro no monitoramento: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'Ã'.(line 2, pos 6)

== SQL ==
SELECT
  REGIÃO AS regiao,
------^^^
  UF AS uf,
  COUNT(ESTACAO) AS quantidade_estacoes,
  SUM(PRECIPITAÇAO) AS volumetria_safra
FROM gold_rainfall
WHERE DATA_FUNDACAO IS NOT NULL
GROUP BY REGIÃO, UF

[2024-07-30T18:53:24.204+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_inmet.py", line 105, in task_monitoramento
    results = monitoramento.execute_monitoramento(spark=spark)
  File "/opt/airflow/plugins/monitoramento_plugin.py", line 87, in execute_monitoramento
    df_result = self.executar_consulta_spark(spark, sql_query)
  File "/opt/airflow/plugins/monitoramento_plugin.py", line 21, in executar_consulta_spark
    df = spark.sql(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 1440, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1323, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'Ã'.(line 2, pos 6)

== SQL ==
SELECT
  REGIÃO AS regiao,
------^^^
  UF AS uf,
  COUNT(ESTACAO) AS quantidade_estacoes,
  SUM(PRECIPITAÇAO) AS volumetria_safra
FROM gold_rainfall
WHERE DATA_FUNDACAO IS NOT NULL
GROUP BY REGIÃO, UF

[2024-07-30T18:53:24.223+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_inmet, task_id=monitoramento_task, execution_date=20240730T183811, start_date=20240730T185320, end_date=20240730T185324
[2024-07-30T18:53:24.238+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2880 for task monitoramento_task (
[PARSE_SYNTAX_ERROR] Syntax error at or near 'Ã'.(line 2, pos 6)

== SQL ==
SELECT
  REGIÃO AS regiao,
------^^^
  UF AS uf,
  COUNT(ESTACAO) AS quantidade_estacoes,
  SUM(PRECIPITAÇAO) AS volumetria_safra
FROM gold_rainfall
WHERE DATA_FUNDACAO IS NOT NULL
GROUP BY REGIÃO, UF
; 13017)
[2024-07-30T18:53:24.259+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-30T18:53:24.279+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
