[2024-07-02T14:38:29.627+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.send_email manual__2024-07-02T14:38:04.257021+00:00 [queued]>
[2024-07-02T14:38:29.638+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.send_email manual__2024-07-02T14:38:04.257021+00:00 [queued]>
[2024-07-02T14:38:29.638+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-02T14:38:29.638+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-07-02T14:38:29.638+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-02T14:38:29.650+0000] {taskinstance.py:1300} INFO - Executing <Task(EmailOperator): send_email> on 2024-07-02 14:38:04.257021+00:00
[2024-07-02T14:38:29.655+0000] {standard_task_runner.py:55} INFO - Started process 495 to run task
[2024-07-02T14:38:29.657+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_teste', 'send_email', 'manual__2024-07-02T14:38:04.257021+00:00', '--job-id', '316', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpmjba4vt2']
[2024-07-02T14:38:29.657+0000] {standard_task_runner.py:83} INFO - Job 316: Subtask send_email
[2024-07-02T14:38:29.697+0000] {task_command.py:388} INFO - Running <TaskInstance: email_teste.send_email manual__2024-07-02T14:38:04.257021+00:00 [running]> on host 159511bdf5fe
[2024-07-02T14:38:29.746+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=testeskleuber@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_teste
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2024-07-02T14:38:04.257021+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-02T14:38:04.257021+00:00
[2024-07-02T14:38:29.753+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-02T14:38:29.754+0000] {email.py:268} INFO - Email alerting: attempt 1
[2024-07-02T14:38:33.002+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.7/smtplib.py", line 735, in login
    raise last_exception
  File "/usr/local/lib/python3.7/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.7/smtplib.py", line 647, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d2e1a72fcca58-708044ac424sm8546923b3a.161 - gsmtp')
[2024-07-02T14:38:33.008+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_teste, task_id=send_email, execution_date=20240702T143804, start_date=20240702T143829, end_date=20240702T143833
[2024-07-02T14:38:33.016+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 316 for task send_email ((535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d2e1a72fcca58-708044ac424sm8546923b3a.161 - gsmtp'); 495)
[2024-07-02T14:38:33.040+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-02T14:38:33.088+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
