[2024-08-21T16:00:52.816+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.process_gold_ts manual__2024-08-21T16:00:14.033771+00:00 [queued]>
[2024-08-21T16:00:52.824+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.process_gold_ts manual__2024-08-21T16:00:14.033771+00:00 [queued]>
[2024-08-21T16:00:52.824+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-21T16:00:52.824+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-21T16:00:52.824+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-21T16:00:52.836+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_gold_ts> on 2024-08-21 16:00:14.033771+00:00
[2024-08-21T16:00:52.842+0000] {standard_task_runner.py:55} INFO - Started process 788 to run task
[2024-08-21T16:00:52.844+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_gold_ts', 'process_gold_ts', 'manual__2024-08-21T16:00:14.033771+00:00', '--job-id', '9884', '--raw', '--subdir', 'DAGS_FOLDER/dag_ts_inmet.py', '--cfg-path', '/tmp/tmpr8qp4ger']
[2024-08-21T16:00:52.845+0000] {standard_task_runner.py:83} INFO - Job 9884: Subtask process_gold_ts
[2024-08-21T16:00:52.884+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_gold_ts.process_gold_ts manual__2024-08-21T16:00:14.033771+00:00 [running]> on host 73b950f14e40
[2024-08-21T16:00:52.931+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_gold_ts
AIRFLOW_CTX_TASK_ID=process_gold_ts
AIRFLOW_CTX_EXECUTION_DATE=2024-08-21T16:00:14.033771+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-21T16:00:14.033771+00:00
[2024-08-21T16:00:55.176+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
  warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)

[2024-08-21T16:01:00.063+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_ts_inmet.py", line 44, in run_gold_ts
    gold_ts.ts_gold(spark)
  File "/opt/airflow/plugins/gold_ts_plugin.py", line 12, in wrapper
    resultado = metodo(*args, **kwargs)
  File "/opt/airflow/plugins/gold_ts_plugin.py", line 70, in ts_gold
    df3 = pd.read_csv(caminho, index_col=0, parse_dates=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/gold/gold_ts/serie_temporal.csv'
[2024-08-21T16:01:00.071+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_gold_ts, task_id=process_gold_ts, execution_date=20240821T160014, start_date=20240821T160052, end_date=20240821T160100
[2024-08-21T16:01:00.087+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9884 for task process_gold_ts ([Errno 2] No such file or directory: '/opt/airflow/data/gold/gold_ts/serie_temporal.csv'; 788)
[2024-08-21T16:01:00.112+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-21T16:01:00.125+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
