[2024-07-23T13:07:45.742+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.process_data scheduled__2024-07-22T13:01:05.460867+00:00 [queued]>
[2024-07-23T13:07:45.750+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.process_data scheduled__2024-07-22T13:01:05.460867+00:00 [queued]>
[2024-07-23T13:07:45.750+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T13:07:45.750+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-07-23T13:07:45.750+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T13:07:45.760+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_data> on 2024-07-22 13:01:05.460867+00:00
[2024-07-23T13:07:45.766+0000] {standard_task_runner.py:55} INFO - Started process 836 to run task
[2024-07-23T13:07:45.768+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_inmet', 'process_data', 'scheduled__2024-07-22T13:01:05.460867+00:00', '--job-id', '691', '--raw', '--subdir', 'DAGS_FOLDER/dag_inmet.py', '--cfg-path', '/tmp/tmp9995d9hg']
[2024-07-23T13:07:45.769+0000] {standard_task_runner.py:83} INFO - Job 691: Subtask process_data
[2024-07-23T13:07:45.921+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_inmet.process_data scheduled__2024-07-22T13:01:05.460867+00:00 [running]> on host 5e3042c0575c
[2024-07-23T13:07:45.969+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_inmet
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-22T13:01:05.460867+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-22T13:01:05.460867+00:00
[2024-07-23T13:07:45.977+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_inmet.py", line 35, in task_process_data
    spark = kwargs['spark']  # Supondo que vocÃª passe um contexto Spark aqui
KeyError: 'spark'
[2024-07-23T13:07:45.982+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_inmet, task_id=process_data, execution_date=20240722T130105, start_date=20240723T130745, end_date=20240723T130745
[2024-07-23T13:07:45.990+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 691 for task process_data ('spark'; 836)
[2024-07-23T13:07:46.019+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-23T13:07:46.034+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
