[2024-08-02T01:32:37.803+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.send_email_normal manual__2024-08-02T01:15:35.301859+00:00 [queued]>
[2024-08-02T01:32:37.813+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.send_email_normal manual__2024-08-02T01:15:35.301859+00:00 [queued]>
[2024-08-02T01:32:37.813+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-02T01:32:37.813+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-02T01:32:37.813+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-02T01:32:37.824+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): send_email_normal> on 2024-08-02 01:15:35.301859+00:00
[2024-08-02T01:32:37.831+0000] {standard_task_runner.py:55} INFO - Started process 13494 to run task
[2024-08-02T01:32:37.833+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_inmet', 'send_email_normal', 'manual__2024-08-02T01:15:35.301859+00:00', '--job-id', '3744', '--raw', '--subdir', 'DAGS_FOLDER/dag_inmet.py', '--cfg-path', '/tmp/tmp4lhaa0ti']
[2024-08-02T01:32:37.834+0000] {standard_task_runner.py:83} INFO - Job 3744: Subtask send_email_normal
[2024-08-02T01:32:37.879+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_inmet.send_email_normal manual__2024-08-02T01:15:35.301859+00:00 [running]> on host 340b192d5d68
[2024-08-02T01:32:37.932+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_inmet
AIRFLOW_CTX_TASK_ID=send_email_normal
AIRFLOW_CTX_EXECUTION_DATE=2024-08-02T01:15:35.301859+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-02T01:15:35.301859+00:00
[2024-08-02T01:32:37.940+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_inmet.py", line 137, in send_email_with_results
    ''',
TypeError: 'NoneType' object is not subscriptable
[2024-08-02T01:32:37.946+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_inmet, task_id=send_email_normal, execution_date=20240802T011535, start_date=20240802T013237, end_date=20240802T013237
[2024-08-02T01:32:37.956+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3744 for task send_email_normal ('NoneType' object is not subscriptable; 13494)
[2024-08-02T01:32:38.004+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-02T01:32:38.018+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
