[2024-08-21T19:08:55.204+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.send_email_results manual__2024-08-21T19:07:08.466740+00:00 [queued]>
[2024-08-21T19:08:55.214+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.send_email_results manual__2024-08-21T19:07:08.466740+00:00 [queued]>
[2024-08-21T19:08:55.214+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-21T19:08:55.214+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-21T19:08:55.214+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-21T19:08:55.226+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): send_email_results> on 2024-08-21 19:07:08.466740+00:00
[2024-08-21T19:08:55.232+0000] {standard_task_runner.py:55} INFO - Started process 5422 to run task
[2024-08-21T19:08:55.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_gold_ts', 'send_email_results', 'manual__2024-08-21T19:07:08.466740+00:00', '--job-id', '10397', '--raw', '--subdir', 'DAGS_FOLDER/dag_ts_inmet.py', '--cfg-path', '/tmp/tmp073arg2t']
[2024-08-21T19:08:55.235+0000] {standard_task_runner.py:83} INFO - Job 10397: Subtask send_email_results
[2024-08-21T19:08:55.278+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_gold_ts.send_email_results manual__2024-08-21T19:07:08.466740+00:00 [running]> on host 2ffd484bc8a9
[2024-08-21T19:08:55.330+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_gold_ts
AIRFLOW_CTX_TASK_ID=send_email_results
AIRFLOW_CTX_EXECUTION_DATE=2024-08-21T19:07:08.466740+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-21T19:07:08.466740+00:00
[2024-08-21T19:08:55.341+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_ts_inmet.py", line 48, in send_email_with_precipitation
    email_config = config['smtp']
KeyError: 'smtp'
[2024-08-21T19:08:55.348+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_gold_ts, task_id=send_email_results, execution_date=20240821T190708, start_date=20240821T190855, end_date=20240821T190855
[2024-08-21T19:08:55.357+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10397 for task send_email_results ('smtp'; 5422)
[2024-08-21T19:08:55.365+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-21T19:08:55.379+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
