[2024-08-28T15:27:00.176+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-28T15:26:09.689380+00:00 [queued]>
[2024-08-28T15:27:00.187+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-28T15:26:09.689380+00:00 [queued]>
[2024-08-28T15:27:00.187+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T15:27:00.187+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-28T15:27:00.187+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T15:27:00.202+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_sarima_forecast> on 2024-08-28 15:26:09.689380+00:00
[2024-08-28T15:27:00.209+0000] {standard_task_runner.py:55} INFO - Started process 20487 to run task
[2024-08-28T15:27:00.211+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sarima_forecast_dag', 'run_sarima_forecast', 'manual__2024-08-28T15:26:09.689380+00:00', '--job-id', '12174', '--raw', '--subdir', 'DAGS_FOLDER/dag_forecast_ts_rainfall.py', '--cfg-path', '/tmp/tmpq64k9nh_']
[2024-08-28T15:27:00.212+0000] {standard_task_runner.py:83} INFO - Job 12174: Subtask run_sarima_forecast
[2024-08-28T15:27:00.268+0000] {task_command.py:388} INFO - Running <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-28T15:26:09.689380+00:00 [running]> on host 4958d38180c6
[2024-08-28T15:27:00.324+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sarima_forecast_dag
AIRFLOW_CTX_TASK_ID=run_sarima_forecast
AIRFLOW_CTX_EXECUTION_DATE=2024-08-28T15:26:09.689380+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-28T15:26:09.689380+00:00
[2024-08-28T15:27:00.576+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_forecast_ts_rainfall.py", line 20, in run_sarima_forecast
    previsoes_df = sarima_plugin.forecast(n_periods=1)
TypeError: forecast() got an unexpected keyword argument 'n_periods'
[2024-08-28T15:27:00.583+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=sarima_forecast_dag, task_id=run_sarima_forecast, execution_date=20240828T152609, start_date=20240828T152700, end_date=20240828T152700
[2024-08-28T15:27:00.591+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12174 for task run_sarima_forecast (forecast() got an unexpected keyword argument 'n_periods'; 20487)
[2024-08-28T15:27:00.624+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-28T15:27:00.639+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
