[2024-07-02T13:17:15.336+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: xcom.tsk1 manual__2024-07-02T13:17:14.229444+00:00 [queued]>
[2024-07-02T13:17:15.344+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: xcom.tsk1 manual__2024-07-02T13:17:14.229444+00:00 [queued]>
[2024-07-02T13:17:15.344+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-02T13:17:15.344+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-02T13:17:15.344+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-02T13:17:15.355+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): tsk1> on 2024-07-02 13:17:14.229444+00:00
[2024-07-02T13:17:15.360+0000] {standard_task_runner.py:55} INFO - Started process 140 to run task
[2024-07-02T13:17:15.362+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'xcom', 'tsk1', 'manual__2024-07-02T13:17:14.229444+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/xcom.py', '--cfg-path', '/tmp/tmpni1ty989']
[2024-07-02T13:17:15.363+0000] {standard_task_runner.py:83} INFO - Job 272: Subtask tsk1
[2024-07-02T13:17:15.405+0000] {task_command.py:388} INFO - Running <TaskInstance: xcom.tsk1 manual__2024-07-02T13:17:14.229444+00:00 [running]> on host 791422d6f0dd
[2024-07-02T13:17:15.457+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-07-02T13:17:14.229444+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-02T13:17:14.229444+00:00
[2024-07-02T13:17:15.457+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xcom.py", line 12, in task_write
    kwarg['ti'].xcom_push(key='valorxcom1',value=10200)
NameError: name 'kwarg' is not defined
[2024-07-02T13:17:15.463+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=xcom, task_id=tsk1, execution_date=20240702T131714, start_date=20240702T131715, end_date=20240702T131715
[2024-07-02T13:17:15.472+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 272 for task tsk1 (name 'kwarg' is not defined; 140)
[2024-07-02T13:17:15.494+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-02T13:17:15.512+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
