[2024-08-22T14:20:18.869+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T14:19:13.364249+00:00 [queued]>
[2024-08-22T14:20:18.876+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T14:19:13.364249+00:00 [queued]>
[2024-08-22T14:20:18.876+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-22T14:20:18.876+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-22T14:20:18.876+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-22T14:20:18.887+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_sarima_forecast> on 2024-08-22 14:19:13.364249+00:00
[2024-08-22T14:20:18.893+0000] {standard_task_runner.py:55} INFO - Started process 486 to run task
[2024-08-22T14:20:18.896+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sarima_forecast_dag', 'run_sarima_forecast', 'manual__2024-08-22T14:19:13.364249+00:00', '--job-id', '10750', '--raw', '--subdir', 'DAGS_FOLDER/dag_forecast_ts_rainfall.py', '--cfg-path', '/tmp/tmpatn39ugj']
[2024-08-22T14:20:18.897+0000] {standard_task_runner.py:83} INFO - Job 10750: Subtask run_sarima_forecast
[2024-08-22T14:20:18.937+0000] {task_command.py:388} INFO - Running <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T14:19:13.364249+00:00 [running]> on host 55d1681e3b54
[2024-08-22T14:20:19.003+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sarima_forecast_dag
AIRFLOW_CTX_TASK_ID=run_sarima_forecast
AIRFLOW_CTX_EXECUTION_DATE=2024-08-22T14:19:13.364249+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-22T14:19:13.364249+00:00
[2024-08-22T14:20:19.226+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_forecast_ts_rainfall.py", line 14, in run_sarima_forecast
    sarima_plugin.load_model()
  File "/opt/airflow/plugins/forecast_ts_rainfall_plugin.py", line 15, in load_model
    self.sarima_model = load(self.model_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.7/pickle.py", line 1436, in load_reduce
    stack[-1] = func(*args)
  File "pandas/_libs/tslibs/timestamps.pyx", line 132, in pandas._libs.tslibs.timestamps._unpickle_timestamp
TypeError: _unpickle_timestamp() takes exactly 3 positional arguments (4 given)
[2024-08-22T14:20:19.233+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=sarima_forecast_dag, task_id=run_sarima_forecast, execution_date=20240822T141913, start_date=20240822T142018, end_date=20240822T142019
[2024-08-22T14:20:19.247+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10750 for task run_sarima_forecast (_unpickle_timestamp() takes exactly 3 positional arguments (4 given); 486)
[2024-08-22T14:20:19.267+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-22T14:20:19.282+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
